In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
train = pd.read_csv('train.csv')
formula_train = pd.read_csv('formula_train.csv')
test = pd.read_csv('test.csv')
formula_test = pd.read_csv('formula_test.csv')

In [4]:
print(train.shape, formula_train.shape)

(17010, 82) (17010, 88)

In [5]:
print(test.shape, formula_test.shape)

(4253, 81) (4253, 87)

In [6]:
train.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,...,2.257143,2.213364,2.219783,1.368922,1.066221,1,1.085714,0.433013,0.437059,29.0
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,...,2.257143,1.888175,2.210679,1.557113,1.047221,2,1.128571,0.632456,0.468606,26.0
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,...,2.271429,2.213364,2.232679,1.368922,1.029175,1,1.114286,0.433013,0.444697,19.0
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,...,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952,22.0
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,...,2.242857,2.213364,2.206963,1.368922,1.096052,1,1.057143,0.433013,0.428809,23.0

In [7]:
test.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,mean_Valence,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence
0,5,92.729214,61.051113,73.132787,37.513930,1.449309,1.146919,122.90607,35.741099,47.094633,...,2.00,2.200000,1.888175,2.124829,1.557113,1.053346,2,1.114286,0.632456,0.550325
1,4,64.632217,55.790060,48.775792,35.178830,1.139875,0.931491,122.90607,35.851917,46.059083,...,2.25,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952
2,4,76.444563,65.834647,59.356672,48.955994,1.199541,1.241867,121.32760,22.132267,43.823354,...,2.25,2.133333,2.213364,2.111100,1.368922,1.354710,1,0.266667,0.433013,0.339935
3,4,96.032850,77.279467,69.515930,53.611120,1.159784,1.267452,151.25960,22.543367,59.663892,...,2.25,2.166667,2.213364,2.139826,1.368922,1.351681,1,0.333333,0.433013,0.372678
4,4,96.451652,75.978308,69.689342,53.146925,1.158346,1.259726,152.93481,24.421050,60.166149,...,2.25,2.116667,2.213364,2.096882,1.368922,1.350047,1,0.316667,0.433013,0.321023

In [8]:
formula_train = formula_train.drop(columns=['critical_temp'])
train_full = pd.concat([train,formula_train], axis = 1)
train_full.drop(columns = ['material'], inplace = True)

In [9]:
train_full.shape

(17010, 168)

In [10]:
train_full.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [11]:
test.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,mean_Valence,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence
0,5,92.729214,61.051113,73.132787,37.513930,1.449309,1.146919,122.90607,35.741099,47.094633,...,2.00,2.200000,1.888175,2.124829,1.557113,1.053346,2,1.114286,0.632456,0.550325
1,4,64.632217,55.790060,48.775792,35.178830,1.139875,0.931491,122.90607,35.851917,46.059083,...,2.25,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952
2,4,76.444563,65.834647,59.356672,48.955994,1.199541,1.241867,121.32760,22.132267,43.823354,...,2.25,2.133333,2.213364,2.111100,1.368922,1.354710,1,0.266667,0.433013,0.339935
3,4,96.032850,77.279467,69.515930,53.611120,1.159784,1.267452,151.25960,22.543367,59.663892,...,2.25,2.166667,2.213364,2.139826,1.368922,1.351681,1,0.333333,0.433013,0.372678
4,4,96.451652,75.978308,69.689342,53.146925,1.158346,1.259726,152.93481,24.421050,60.166149,...,2.25,2.116667,2.213364,2.096882,1.368922,1.350047,1,0.316667,0.433013,0.321023

In [12]:
formula_test.head()

,H,He,Li,Be,B,C,N,O,F,Ne,...,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn,material
0,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Ba0.1La1.9Ag0.5Cu0.5O4
1,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,La1.85Ca0.15Cu1O4
2,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Y0.4Ba0.6Cu1O
3,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Er0.5Ba0.5Cu1O
4,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Tm0.35Ba0.65Cu1O

In [13]:
test_full = pd.concat([test,formula_test], axis = 1)
test_full.drop(columns = ['material'], inplace = True)

In [14]:
test_full.shape

(4253, 167)

In [15]:
x = train_full.drop(columns=['critical_temp'])
y = train_full['critical_temp']

In [16]:
x.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [17]:
y.head()

0    29.0
1    26.0
2    19.0
3    22.0
4    23.0
Name: critical_temp, dtype: float64

In [18]:
y.shape

(17010,)

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)

In [20]:
print('Размерность тренировочного датасета')
print(x_train.shape, y_train.shape)

Размерность тренировочного датасета
(11907, 167) (11907,)

In [21]:
print('Размерность тестового датасета')
print(x_test.shape, y_test.shape)

Размерность тестового датасета
(5103, 167) (5103,)

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [23]:
model = LinearRegression()

In [24]:
model.fit(x_train, y_train)

LinearRegression()

In [25]:
print(model.coef_)
print(model.intercept_)

[ 1.05538546e+00  9.61515977e-01 -1.35447923e+00 -5.00963268e-01
  8.04554329e-01 -2.43357552e+01  2.36208804e+00  1.78693308e-01
  1.11472459e-01 -5.52489736e-01  9.11284091e-02 -1.84925240e-01
  4.83054117e-02  1.46613119e-01  1.32156409e-03 -1.52589349e+01
  5.62564019e+01  4.67228509e-02  1.70638026e-02 -6.59004916e-02
 -6.12062131e-02 -7.99090610e-01  2.22313013e+00  5.31931127e-01
 -1.94761113e+00 -2.71832961e+01  2.12866518e+01  4.57222718e-02
 -7.28501481e-02 -2.07640606e-01 -8.24122171e-02 -5.68980238e-03
  5.35244831e-03  9.51628090e-04 -6.25257232e-04 -9.19416683e+00
  1.33876672e+00 -7.80169366e-04 -4.53487127e-04  3.29694999e-03
 -1.51762715e-03 -5.76148484e-02  3.68944256e-01  1.11798195e-01
 -4.15866170e-01  1.14272293e+01 -1.92184452e+01 -3.22387337e-01
 -9.58364315e-02  1.12914639e+00 -4.48363724e-01  1.23015079e+00
 -1.77823778e+00 -8.67311923e-01  1.29227875e+00 -1.86037267e+01
  2.39409661e+01 -7.13827917e-02  6.18238997e-01 -1.18381046e+00
  8.52705789e-01 -5.62680950e-02  4.88312434e-01 -4.74618495e-02
 -3.47454138e-01  1.47885451e+01  3.86074668e-01 -1.17476870e-01
 -1.94806907e-01  3.38901806e-01  2.02036237e-02  3.61280804e+00
 -8.21406884e+00  1.19746101e+00  3.93365085e+00  6.81965041e+01
 -7.72430813e+01  3.84537736e+00 -2.18268770e+00  4.00773585e+00
 -1.81611998e+01 -7.61226425e-01 -2.96251912e-12  3.62682800e+00
 -2.69255814e-01 -1.12809479e+00 -1.59833979e-01  1.61046904e+00
 -5.21251652e-01  5.24296655e+00  1.40421008e-12  6.71882487e+00
  1.35978199e+00 -7.39824900e-02 -1.53617221e+00 -1.50274758e+00
 -2.19710314e+00 -8.46840726e+00  3.94351218e-13  1.01847047e+01
  1.12798547e+00  4.55242871e-01 -3.46382175e-02 -5.17529827e-03
 -2.60759377e-01  6.29711809e-01  9.66069941e-01 -7.39599823e-01
 -3.13226324e-01 -5.01795117e-01 -7.37012829e-02  5.34239876e-01
 -9.89191285e-01 -1.37409922e+00 -1.05165210e+00 -2.73528316e+00
 -2.23820962e-13  1.16675109e+01  6.47046352e-01 -4.17888866e-01
  5.32689651e-03  6.88459420e-02  1.50040584e-01  1.33325177e+00
  2.09656897e-01 -1.80090498e-01  1.62486694e-02 -1.08387338e+01
 -1.45955565e-01  9.56179168e-01 -8.92921611e-02 -1.03607013e-01
  3.32920398e-01  6.17363195e+00 -1.58983937e-13  6.80808094e+00
  8.57405559e+00  3.13112182e-02 -1.36476995e+00  1.47264529e-02
 -1.38270508e+00 -1.86517468e-14  9.40186161e-01 -2.46714245e+00
 -1.58794614e+00  1.79747792e+00  5.36209619e+00  3.32701931e+00
  2.63016730e+00  7.04344050e-01  1.83691594e+00  3.62787236e+00
 -7.03394873e-01  7.35422130e-02  7.22157977e-01 -1.12427725e-01
  1.04133181e+00 -1.01916292e-01  3.60498788e+00 -1.02846749e+00
  7.76343731e+00  5.56292180e+00  2.60311778e+00  6.67175500e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00]
0.9644892472820388

In [26]:
features = test_full.columns

In [27]:
coeff_df = pd.DataFrame(model.coef_,columns = ['coefficient'])

In [28]:
coeff_df['features'] = features

In [29]:
coeff_df.shape

(167, 2)

In [30]:
coeff_df.sort_values(by='coefficient')

    coefficient                      features
76   -77.243081           wtd_entropy_Valence
25   -27.183296         entropy_atomic_radius
5    -24.335755           entropy_atomic_mass
46   -19.218445  wtd_entropy_ElectronAffinity
55   -18.603727            entropy_FusionHeat
..          ...                           ...
65    14.788545   entropy_ThermalConductivity
26    21.286652     wtd_entropy_atomic_radius
56    23.940966        wtd_entropy_FusionHeat
16    56.256402               wtd_entropy_fie
75    68.196504               entropy_Valence

[167 rows x 2 columns]

In [31]:
y_pred = model.predict(x_test)
print(mean_absolute_error(y_pred, y_test))
print(mean_squared_error(y_pred, y_test))
print(r2_score(y_pred, y_test))

12.524724284803394
281.7218049856615
0.6907127586443942

In [32]:
y_pred_test = model.predict(test_full)
y_pred_test = pd.DataFrame(y_pred_test, columns = ['critical_temp'])
y_pred_test = y_pred_test.reset_index()
y_pred_test.to_csv('solution.csv', index = False)