In [11]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
train = pd.read_csv('train.csv')
formula_train = pd.read_csv('formula_train.csv')
test = pd.read_csv('test.csv')
formula_test = pd.read_csv('formula_test.csv')

In [5]:
print(train.shape, formula_train.shape)

(17010, 82) (17010, 88)

In [6]:
print(test.shape, formula_test.shape)

(4253, 81) (4253, 87)

In [7]:
train.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,...,2.257143,2.213364,2.219783,1.368922,1.066221,1,1.085714,0.433013,0.437059,29.0
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,...,2.257143,1.888175,2.210679,1.557113,1.047221,2,1.128571,0.632456,0.468606,26.0
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,...,2.271429,2.213364,2.232679,1.368922,1.029175,1,1.114286,0.433013,0.444697,19.0
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,...,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952,22.0
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,...,2.242857,2.213364,2.206963,1.368922,1.096052,1,1.057143,0.433013,0.428809,23.0

In [8]:
test.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,mean_Valence,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence
0,5,92.729214,61.051113,73.132787,37.513930,1.449309,1.146919,122.90607,35.741099,47.094633,...,2.00,2.200000,1.888175,2.124829,1.557113,1.053346,2,1.114286,0.632456,0.550325
1,4,64.632217,55.790060,48.775792,35.178830,1.139875,0.931491,122.90607,35.851917,46.059083,...,2.25,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952
2,4,76.444563,65.834647,59.356672,48.955994,1.199541,1.241867,121.32760,22.132267,43.823354,...,2.25,2.133333,2.213364,2.111100,1.368922,1.354710,1,0.266667,0.433013,0.339935
3,4,96.032850,77.279467,69.515930,53.611120,1.159784,1.267452,151.25960,22.543367,59.663892,...,2.25,2.166667,2.213364,2.139826,1.368922,1.351681,1,0.333333,0.433013,0.372678
4,4,96.451652,75.978308,69.689342,53.146925,1.158346,1.259726,152.93481,24.421050,60.166149,...,2.25,2.116667,2.213364,2.096882,1.368922,1.350047,1,0.316667,0.433013,0.321023

In [9]:
formula_train = formula_train.drop(columns=['critical_temp'])
train_full = pd.concat([train,formula_train], axis = 1)
train_full.drop(columns = ['material'], inplace = True)

In [10]:
train_full.shape

(17010, 168)

In [12]:
train_full.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [13]:
test.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,mean_Valence,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence
0,5,92.729214,61.051113,73.132787,37.513930,1.449309,1.146919,122.90607,35.741099,47.094633,...,2.00,2.200000,1.888175,2.124829,1.557113,1.053346,2,1.114286,0.632456,0.550325
1,4,64.632217,55.790060,48.775792,35.178830,1.139875,0.931491,122.90607,35.851917,46.059083,...,2.25,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952
2,4,76.444563,65.834647,59.356672,48.955994,1.199541,1.241867,121.32760,22.132267,43.823354,...,2.25,2.133333,2.213364,2.111100,1.368922,1.354710,1,0.266667,0.433013,0.339935
3,4,96.032850,77.279467,69.515930,53.611120,1.159784,1.267452,151.25960,22.543367,59.663892,...,2.25,2.166667,2.213364,2.139826,1.368922,1.351681,1,0.333333,0.433013,0.372678
4,4,96.451652,75.978308,69.689342,53.146925,1.158346,1.259726,152.93481,24.421050,60.166149,...,2.25,2.116667,2.213364,2.096882,1.368922,1.350047,1,0.316667,0.433013,0.321023

In [14]:
formula_test.head()

,H,He,Li,Be,B,C,N,O,F,Ne,...,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn,material
0,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Ba0.1La1.9Ag0.5Cu0.5O4
1,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,La1.85Ca0.15Cu1O4
2,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Y0.4Ba0.6Cu1O
3,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Er0.5Ba0.5Cu1O
4,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Tm0.35Ba0.65Cu1O

In [15]:
test_full = pd.concat([test,formula_test], axis = 1)
test_full.drop(columns = ['material'], inplace = True)

In [17]:
test_full.shape

(4253, 167)

In [19]:
x = train_full.drop(columns=['critical_temp'])
y = train_full['critical_temp']

In [20]:
x.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [22]:
y.head()

0    29.0
1    26.0
2    19.0
3    22.0
4    23.0
Name: critical_temp, dtype: float64

In [25]:
y.shape

(17010,)

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)

In [28]:
print('Размерность тренировочного датасета')
print(x_train.shape, y_train.shape)

Размерность тренировочного датасета
(11907, 167) (11907,)

In [30]:
print('Размерность тестового датасета')
print(x_test.shape, y_test.shape)

Размерность тестового датасета
(5103, 167) (5103,)

In [34]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [38]:
model = LinearRegression()

In [40]:
model.fit(x_train, y_train)

LinearRegression()

In [58]:
print(model.coef_)
print(model.intercept_)

[ 1.19958809e+00  9.64228146e-01 -1.36566184e+00 -4.89505433e-01
  7.90988075e-01 -1.84280061e+01 -8.75768091e-01  2.11124685e-01
  1.23274499e-01 -5.56140163e-01  2.51094662e-02 -1.57011553e-01
 -1.43156570e-02  1.16925058e-01  7.09007087e-02  9.50026100e-02
  5.44178386e+01  3.60708185e-02  2.10068725e-02 -8.02179866e-02
 -9.67224191e-03 -8.53669810e-01  2.02079678e+00  5.75146963e-01
 -1.72074559e+00 -5.61549229e+01  2.48446889e+01  3.82165567e-02
 -6.46890601e-02 -2.19525147e-01 -9.63093067e-02 -5.59191723e-03
  6.10653371e-03  6.11763909e-04 -1.10500334e-03 -1.16330187e+01
  3.19157345e+00 -1.09506063e-03 -7.54009510e-04  3.65010216e-03
 -1.27671514e-03 -1.33617214e-02  3.22368458e-01  8.40660827e-02
 -3.83880405e-01  1.15867770e+01 -1.91423911e+01 -3.10739122e-01
 -8.68846518e-02  1.11255432e+00 -4.72104384e-01  1.14351116e+00
 -1.69234520e+00 -8.07136023e-01  1.20301499e+00 -1.67153404e+01
  2.29984097e+01 -7.03814383e-02  6.00440740e-01 -9.92993291e-01
  7.24742170e-01 -1.01692842e-01  5.41506869e-01 -3.30393799e-02
 -3.76158100e-01  1.77611703e+01 -6.24114315e-01 -1.28435854e-01
 -2.19508479e-01  4.17318479e-01 -1.85274050e-02  1.44558482e+01
 -2.19186250e+01 -1.00170266e+01  1.83213615e+01  7.36574748e+01
 -7.50814759e+01  4.20815002e+00 -2.45585571e+00  4.89214918e-01
 -1.45592818e+01 -9.73448746e-01 -2.68318701e-12  4.11000088e+00
 -2.51760718e-01 -2.98767537e-01 -2.86236684e-01  1.58165230e-01
 -8.00921276e-01  8.45175425e+00 -1.11528564e-11  1.01851588e+01
  2.80478378e-01 -6.24980048e-02 -1.93923714e+00 -1.62329253e+00
 -2.23996810e+00 -7.86119621e+00 -1.27897692e-12  1.24448349e+01
  1.34562683e+00  9.87104618e-01 -1.52237792e-01  9.74704198e-02
 -3.43626142e-01  3.10567025e-01  1.13883721e+00 -8.54551331e-01
 -4.36084843e-01 -4.81960516e-01 -2.29783242e-01  2.84863107e-01
 -1.39259102e+00 -1.59676827e+00 -1.19684444e+00 -3.51035613e+00
  1.33582034e-12  1.34576029e+01  8.32867190e-01 -8.64364698e-02
  4.94648898e-03  1.08516362e-01  1.58496495e-01  2.60529521e+00
  2.86556856e-01 -1.85608351e-01  1.01746317e-01 -1.22821735e+01
 -1.42016682e-01  1.38082245e+00 -1.37734728e-01 -1.87689581e-01
  4.30314405e-01  5.88944240e+00  3.96127575e-13  1.17555367e+01
  1.06436632e+01  2.85850352e-03 -2.76449030e+00  3.94186810e-02
 -1.36917168e+00 -6.10622664e-14 -6.62293892e-01 -7.98179737e-01
 -3.02175881e-01 -5.26287507e-01  4.46111142e+00  2.02284198e+00
  2.08359597e+00  1.11706440e+00  3.32419193e+00  4.51194464e+00
 -4.11969149e-01  7.13337395e-02  1.72281866e+00 -7.34822747e-02
  1.07895238e+00 -7.96332595e-02  3.66261106e+00 -5.88157962e-01
  6.25893398e+00  5.65600126e+00  2.21625558e+00  7.38286578e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00]
-5.544388181964258

In [53]:
features = test_full.columns

In [54]:
coeff_df = pd.DataFrame(model.coef_,columns = ['coefficient'])

In [55]:
coeff_df['features'] = features

In [56]:
coeff_df.shape

(167, 2)

In [57]:
coeff_df.sort_values(by='coefficient')

    coefficient                      features
76   -75.081476           wtd_entropy_Valence
25   -56.154923         entropy_atomic_radius
72   -21.918625              wtd_mean_Valence
46   -19.142391  wtd_entropy_ElectronAffinity
5    -18.428006           entropy_atomic_mass
..          ...                           ...
74    18.321361             wtd_gmean_Valence
56    22.998410        wtd_entropy_FusionHeat
26    24.844689     wtd_entropy_atomic_radius
16    54.417839               wtd_entropy_fie
75    73.657475               entropy_Valence

[167 rows x 2 columns]

In [61]:
y_pred = model.predict(x_test)
print(mean_absolute_error(y_pred, y_test))
print(mean_squared_error(y_pred, y_test))
print(r2_score(y_pred, y_test))

12.489425505335365
281.64592300455536
0.6993327490793181

In [66]:
y_pred_test = model.predict(test_full)
y_pred_test = pd.DataFrame(y_pred_test, columns = ['critical_temp'])
y_pred_test = y_pred_test.reset_index()
y_pred_test.to_csv('solution.csv')